name: build-push-container-to-acr
run-name: Build & Push ${{ github.event.inputs.dockerfile_dir }} to ACR

on:
  workflow_dispatch:
    inputs:
      dockerfile_dir:
        type: choice
        description: Dockerfile dir
        options: 
          - github-runners
      runners:
        type: choice
        description: Github runner type
        default: self-hosted
        options: 
          - ubuntu-latest
          - self-hosted

env:
  ACR_NAME: acrglbuksdevopsutils
  ACR_SERVER_NAME: acrglbuksdevopsutils.azurecr.io
  TAG: ${{ github.run_number }}

permissions:
  id-token: write

jobs:
  build_and_push:
    runs-on: ${{ github.event.inputs.runners }}
    environment: glb
    defaults:
      run:
        working-directory: ./${{ github.event.inputs.dockerfile_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Build ${{ github.event.inputs.dockerfile_dir }} (in ACR)
        run: |
          # This utilizes the acr task created in ../iac/devopsutils/create_acr_task.yaml
          az acr task run -r $ACR_NAME -n build_and_push_image --set image_name=${{ github.event.inputs.dockerfile_dir }} --set dockerfile=Dockerfile -c .