name: build-push-container-to-acr
run-name: Build & Push ${{ github.event.inputs.dockerfile_dir }} to ACR

on:
  workflow_dispatch:
    inputs:
      dockerfile_dir:
        type: choice
        description: Dockerfile dir
        options: 
          - github-runners

env:
  ACR_NAME: acrglbuksdevopsutils
  ACR_SERVER_NAME: acrglbuksdevopsutils.azurecr.io
  TAG: ${{ github.run_number }}

permissions:
  id-token: write

jobs:
  build_and_push:
    runs-on: self-hosted
    environment: glb
    defaults:
      run:
        working-directory: ./${{ github.event.inputs.dockerfile_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Build image (in ACR)
        run: |
          az acr task run -n build_and_push_task -r acrglbuksdevopsutils -c . -f acr_task.yml

          # az acr task create \
          #   --registry ${{ env.ACR_SERVER_NAME }} \
          #   --name buildAndPushTask \
          #   --image "${{ github.event.inputs.dockerfile_dir }}:${{ env.TAG }}" \
          #   --file Dockerfile \
        
          # # az acr build actually copies the files to the ACR and its built there...
          # az acr build \
          #   --registry ${{ env.ACR_SERVER_NAME }} \
          #   --image "${{ github.event.inputs.dockerfile_dir }}:${{ env.TAG }}" \
          #   --build-arg build_version=${{ env.TAG }} .

          # # Also tag with latest
          # az acr import --name ${{ env.ACR_SERVER_NAME }} --source "${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.dockerfile_dir }}:${{ env.TAG }}" --image ${{ github.event.inputs.dockerfile_dir }}:latest --force

