name: build-push-container-to-acr
run-name: Build & Push container to ACR

on:
  workflow_dispatch:
    inputs:
      dockerfile_dir:
        type: choice
        description: Dockerfile dir
        options: 
          - self-hosted-runners

env:
  ACR_NAME: acrglbuksdevops01
  ACR_SERVER_NAME: acrglbuksdevops01.azurecr.io
  REPOSITORY_NAME: devops
  TAG: ${{ github.run_number }}

permissions:
  id-token: write

jobs:
  dockerize:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./${{ github.event.inputs.dockerfile_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Docker build
        run: docker build -t ${{ env.ACR_SERVER_NAME }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }} --build-arg build_version=${{ env.TAG }} .

      - name: Docker push
        run: docker push ${{ env.ACR_SERVER_NAME }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}