name: build-push-container-to-acr
run-name: Build & Push ${{ github.event.inputs.dockerfile_dir }} to ACR

on:
  workflow_dispatch:
    inputs:
      image_name:
        type: choice
        description: Image name
        options: 
          - github-runners
      runners:
        type: choice
        description: Github runner type
        default: ubuntu-latest
        options: 
          - ubuntu-latest
          # - self-hosted

env:
  ACR_SERVER_NAME: acrglbuksdevopsutils.azurecr.io
  TAG: ${{ github.run_number }}

permissions:
  id-token: write

jobs:
  build_and_push:
    runs-on: ${{ github.event.inputs.runners }}
    environment: glb
    defaults:
      run:
        working-directory: ./images/${{ github.event.inputs.image_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name ${{ env.ACR_SERVER_NAME }}

      - name: Docker build
        run: |
          docker build -t "${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.image_name }}:${{ env.TAG }}" .
          
          docker tag "${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.image_name }}:${{ env.TAG }}" "${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.image_name }}:latest"

      - name: Docker push
        run: |
          docker push ${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.image_name }}:${{ env.TAG }}
          docker push ${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.image_name }}:latest
