name: build-push-container-to-acr
run-name: Build & Push ${{ github.event.inputs.dockerfile_dir }} to ACR

on:
  workflow_dispatch:
    inputs:
      dockerfile_dir:
        type: choice
        description: Dockerfile dir
        options: 
          - github-runners

env:
  ACR_NAME: acrglbuksdevopsutils
  ACR_SERVER_NAME: acrglbuksdevopsutils.azurecr.io
  TAG: ${{ github.run_number }}

permissions:
  id-token: write

jobs:
  build_and_push:
    runs-on: self-hosted
    environment: glb
    defaults:
      run:
        working-directory: ./${{ github.event.inputs.dockerfile_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Docker build
        run: |
          docker build -t ${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.dockerfile_dir }}:${{ env.TAG }} --build-arg build_version=${{ env.TAG }} .
          docker tag ${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.dockerfile_dir }}:${{ env.TAG }} ${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.dockerfile_dir }}:latest

      - name: Docker push
        run: |
          docker push ${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.dockerfile_dir }}:${{ env.TAG }}
          docker push ${{ env.ACR_SERVER_NAME }}/${{ github.event.inputs.dockerfile_dir }}:latest