name: Save hosting costs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"  # Runs every day at 11 PM UTC

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Run save_cost.yml script
        run: bash ./.github/scripts/save_cost.sh ${{ vars.AZURE_SUBSCRIPTION_ID }}
