name: destroy-ghrunners-infra
run-name: Terraform destroy ${{ github.event.inputs.app_name }} in ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
          - glb
      app_name:
        type: choice
        description: Application name
        options: 
          - ghrunners

env:
 ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
 ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
 ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
 ARM_USE_AZUREAD: true
 work_dir: ./iac/${{ github.event.inputs.app_name }}
 DEVOPS_KEY_VAULT_NAME: kv-glb-uks-devopsutils
 GITHUB_APP_SECRET_NAME: github-app-key

permissions:
  id-token: write
  contents: read

jobs:
  fetch_runner_secret: 
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      SECRET_URI: ${{ steps.insert_secret.outputs.SECRET_URI }}
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      
      - name: Make Key Vault public
        run:  ../scripts/make_keyvault_public.sh

      - name: Get secret URI a secret in Azure Key Vault
        id: insert_secret
        run: |
          SECRET_URI=$(az keyvault secret show --vault-name "${{ env.DEVOPS_KEY_VAULT_NAME }}" --name "${{ env.GITHUB_APP_SECRET_NAME }}" --query "id" -o tsv)
          echo "SECRET_URI=$SECRET_URI" >> $GITHUB_OUTPUT
          
  terraform_plan_destroy:
    needs: fetch_runner_secret 
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ${{ env.work_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform plan destroy
        uses: davejg10/pipeline_templates/.github/actions/terraform_plan_destroy@v1
        with:
          backend_azure_resource_group_name: ${{ vars.backend_azure_resource_group_name }}
          backend_azure_storage_account_name: ${{ vars.backend_azure_storage_account_name }}
          backend_container_name: ${{ github.event.inputs.app_name }}
          environment: ${{ github.event.inputs.environment }}
          work_dir: ${{ env.work_dir }}
          additional_tf_vars: -var "github_app_key_secret_id=${{ needs.fetch_runner_secret.outputs.SECRET_URI }}" -var "github_app_key_secret_name=${{ env.GITHUB_APP_SECRET_NAME }}" -var "github_installation_id=${{ vars.GH_INSTALLATION_ID }}" -var "github_app_id=${{ vars.GH_APP_ID }}"

  terraform_apply:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    needs: terraform_plan_destroy
    defaults:
      run:
        working-directory: ${{ env.work_dir }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform apply
        uses: davejg10/pipeline_templates/.github/actions/terraform_apply@v1
        with:
          backend_azure_resource_group_name: ${{ vars.backend_azure_resource_group_name }}
          backend_azure_storage_account_name: ${{ vars.backend_azure_storage_account_name }}
          backend_container_name: ${{ github.event.inputs.app_name }}
          work_dir: ${{ env.work_dir }}