name: terraform-destroy
run-name: Terraform destroy ${{ github.event.inputs.app_name }} in ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
          - glb
      app_name:
        type: choice
        description: Application name
        options: 
          - devopsutils
          - ghrunners
      runners:
        type: choice
        description: Github runner type
        default: self-hosted
        options: 
          - ubuntu-latest
          - self-hosted

env:
 ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
 ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
 ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
 ARM_USE_AZUREAD: true
 work_dir: ./iac/${{ github.event.inputs.app_name }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ${{ env.work_dir }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=${{ vars.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ github.event.inputs.app_name }}"
            
      - name: Terraform destroy ${{ github.event.inputs.app_name }}
        if: ${{ github.event.inputs.app_name }} == ghrunners
        run: |
          terraform destroy -auto-approve \
            -var "github_app_key_secret_name=github-app-key" \
            -var "github_installation_id=${{ vars.GH_INSTALLATION_ID }}" \
            -var "github_app_id=${{ vars.GH_APP_ID }}" \
            -var-file="tfvars/${{ github.event.inputs.environment }}/main.tfvars"

      - name: Terraform destroy
        if: ${{ github.event.inputs.app_name }} == devopsutils
        run: |
          terraform destroy -auto-approve \
            -var-file="tfvars/${{ github.event.inputs.environment }}/main.tfvars"