name: Test self-hosted runners

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: self-hosted

    steps:

      - run: |
          az login --identity -u $MSI_CLIENT_ID
          
        name: Execute az cli sample commands