name: Test self-hosted runners

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: |
          . /etc/profile.d/jdk.sh

          java -version
        name: Execute az cli sample commands
        shell: bash