name: Test self-hosted runners

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: build packages
        run: make all
        
      - run: |
          yq
          docker
        name: Execute az cli sample commands