name: Test self-hosted runners

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: |
          ps -p $$ -o comm=
        name: Execute az cli sample commands